# Numpy .

La librería NumPy es una librería cuyo objeto principal es la estructura multidimensional **ndarray** (conocido también como **array**, cuenta además con un conjunto amplio de herramientas para su gestión, funciones matemáticas, funciones de alto nivel del álgebra lineal y herramientas para la generación de números pseudo-aleatorios (En el Tema 5, aclararemos el concepto de números aleatorios y pseudo-aleatorios).

E **ndarray**s una tabla de elementos (normalmente números) donde todos ellos son del mismo tipo, indizados por una tupla de enteros positivos. En NumPy las *dimensiones* son llamadas <font color="red">ejes</font>. Al número de ejes se llama <font color="blue">rango</font>.

Por ejemplo, las coordenadas de un punto en el espacio 3D $[1,2,1]$ es un arreglo de rango $1$, ya que tiene sólo un eje. Ese eje tiene una longitud de $3$.

Veamos el siguiente arreglo:
$$
\begin{align*}
[[1., 0., 0.], \\
[0., 1., 2. ]]
\end{align*}
$$
El arreglo es de rango $2$ (por que es de dimensión $2$), la primera dimensión (o eje) tiene una longitud de $2$, la segunda dimensión tiene longitud $3$.

La clase en NumPy para arreglos es **ndarray**, que también es conocido con el alias de **array**. Nótese que **numpy.array** no es el mismo elemento de la librería estándar de python *array.array*, ya que ésta sólo maneja arreglos de 1D y ofrece menos funcionalidad.


## Atributos del ndarray.

Los atributos más importantes de un objeto **ndarray** son:
1. <code>ndarray.dim</code>: es el número de ejes en el arreglo. En el universo python, el número de dimensiones se conoce como *rango*.
2. <code>ndarray.shape</code>: son las dimensiones del arreglo. Es una tupla de enteros que indican el tamaño del arreglo en cada dimensión. Para un arreglo (matriz) con $n$ renglones y $m$ columnas, *shape* será $(n,m)$. La longitud de la tupla *shape*, es por tanto el rango, o número de dimensiones, *ndim*.
3. <code>ndarray.size</code>: es el total de número de elementos en el arreglo. Es igual al producto de los elementos de *shape*.
4. <code>ndarray.dtype</code>: es un objeto que describe el tipo de elementos en el arreglo. Podemos crear un d-tipeado específico, usando los tipos estándar de python; Numpy proporciona tipos propios: <code>numpy.int32</code>, <code>numpy.int16</code> y <code>numpy.float64</code> como ejemplos.
5. <code>ndarray.itemsize</code>: devuelve el tamaño en bytes de cada elemento del arreglo. Por ejemplo, un arreglo de elementos de tipo <code>float64</code> tiene un <code>itemsize 8</code> $(=64/8)$, mientras que uno de tipo <code>complex32</code> tiene un <code>itemsize 4</code> $(=32/8)$.

### Ejemplos.

In [4]:
from numpy import *

a = arange(15).reshape(3, 5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int64'

In [10]:
a.size

15

In [9]:
a.itemsize

8

In [11]:
type(a)

numpy.ndarray

In [15]:
b = array([6, 7, 8])

In [16]:
b

array([6, 7, 8])

In [17]:
type(b)

numpy.ndarray

# Creando un arreglo.

Podemos crear un arreglo de diferentes maneras. Por ejemplo, podemos crear un arreglo de una lista o tupla regular de python, usando la función <code>array</code>. El tipo de de arreglo resultante se deduce del tipo de elementos en la secuencia.

In [18]:
c = array([2, 3, 4])

In [20]:
c

array([2, 3, 4])

In [21]:
c.dtype

dtype('int64')

In [22]:
d = array ([1.2, 3.5, 5.1])

In [23]:
d.dtype

dtype('float64')

## Precaución,

Un error que se presenta frecuentemente es llamar a la función <code>array</code> con múltiples argumentos, en lugar de proporcionar una  única lista de números.

<strong><code><font color="red">Mal hecho: </font></code></strong> <code>a = array (1,2,3,4)</code>

<strong><code><font color="green">Bien hecho: </font></code></strong> <code>a = array ([1,2,3,4])</code>

A menudo, los elementos de un arreglo no se conocen desde el inicio del problema, pero su tamaño si; Numpy proporciona algunas funciones que generan arreglos con un contenido inicial, con la finalidad de minimizar el crecimiento de arreglos, que es a su vez, una tarea que gasta recursos.

1. <code>zeros</code>: genera un arreglo donde todos los elementos son ceros.

2. <code>ones</code>: genera un arreglo donde todos los elementos del mismo son unos.

3. <code>empty</code>: genera un arreglo con valores iniciales aleatorios, por defecto, el tipo de dato es <code>float64</code>.

In [24]:
zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
a5 = ones((2, 3, 4))

In [33]:
a5

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
a5.dtype

dtype('float64')

In [36]:
a6 = ones((2, 3, 4), dtype='int16')

In [37]:
a6

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [38]:
a6.dtype

dtype('int16')

In [47]:
a7 = empty((2, 3))

In [50]:
a7 # El resultado puede variar dependiendo del estado de la memoria

array([[0.3, 0.6, 0.9],
       [1.2, 1.5, 1.8]])

In [51]:
a7.dtype

dtype('float64')

## La función arange.

Para crear una secuencia de números, Numpy cuenta con una función  análoga a *range*, que devuelve arreglos en lugar de listas.

Toma en cuenta los argumentos de la función:
$$arange(\text{inicio}, \text{fin}, \text{paso})$$

Donde:
1. *inicio*: es el valor donde comienza la secuencia.
2. *fin*: es el valor donde termina la secuencia, pero **no** está incluido en la misma.
3. *paso*: es un argumento opcional, indica el incremento en la secuencia.

Se pueden generar secuencias con valores enteros o de punto flotante.

In [41]:
arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arange(10, 30, 5)

array([10, 15, 20, 25])

In [40]:
arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

## La función linspace.

Cuando se utiliza la función *arange* con argumentos de punto flotante, en general no es posible predecir el número de elementos obtenidos, debido a la precisión de punto flotante. Por tanto, es mejor usar la función **linspace**, en el argumento de la función, se indica el número de elementos que queremos, en vez de un paso.

In [42]:
linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [43]:
x = linspace(0, 2*pi, 100)

f = sin(x)

In [44]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [45]:
len(f)

100

In [54]:
y3 = arange(10000)

In [56]:
y3 # Si el contenido del arreglo es muy extenso, se presentan solo unos cuantos elementos dejando puntos suspensivos entre los valore

array([   0,    1,    2, ..., 9997, 9998, 9999])

# Operaciones básicas.

Los operaciones aritméticas en los arreglos se realizan *elemento a elemento*. Se genera un nuevo arreglo para mostrar el resultado.

In [59]:
x1 = array([20, 30, 40, 50])
x2 = arange(4)

In [60]:
x1

array([20, 30, 40, 50])

In [61]:
x2

array([0, 1, 2, 3])

In [64]:
c = x1 - x2

In [65]:
c

array([20, 29, 38, 47])

In [66]:
x2**2

array([0, 1, 4, 9])

In [68]:
10 * cos(x2)

array([10.        ,  5.40302306, -4.16146837, -9.89992497])

In [69]:
x1 < 35

array([ True,  True, False, False])

## Operador producto.

Como ya mencionamos, las operaciones artiméticas se realizan elemento a elemento, como en el caso del operador <code>*</code>. El producto entre matrices se obtiene mediante el operador <code>@</code> (en versiones de python >= 3.5) o mediante la función <code>dot</code>

In [70]:
A = array([[1, 1], [0, 1]])

B = array([[2, 0], [3, 4]])

In [71]:
A * B     # producto elemento por elemento

array([[2, 0],
       [0, 4]])

In [72]:
A @ B     # producto de matrices

array([[5, 4],
       [3, 4]])

In [73]:
A.dot(B)  # producto de matrices

array([[5, 4],
       [3, 4]])